language: ruby
cache: bundler
rvm:
  - 2.2.0
notifications:
  slack: cs4500-team8:zbNze7PM1dr45x7LikU71lYA
  email:
    recipients:
      - steve@steve-pletcher.com
    on_success: change
    on_failure: change
services:
  - postgresql
before_script:
  - psql -c 'create database wedikopg_travis;' -U postgres
  - cp config/database.yml.travis config/database.yml
